sudo: true
language: python
python: 
  - "3.7"

dist: xenial

install:
  - pip install pipenv

script:
  - pipenv install --dev && pipenv run pip install -e ./ && pipenv run pytest --cov==StaticFlask -v
